import { useState, useMemo } from 'react';
import { HostBooking, HostProperty, HostReview, HostAccount } from '@/pages/admin/types';

interface Props {
  host: HostAccount;
  bookings: HostBooking[];
  properties: HostProperty[];
  reviews: HostReview[];
}

type ReportType = 'earnings' | 'bookings' | 'tax' | 'gst';

interface MonthlyGroup {
  key: string;
  label: string;
  year: number;
  month: number;
  bookings: HostBooking[];
  grossRevenue: number;
  platformFee: number;
  netEarnings: number;
  bookingCount: number;
  totalNights: number;
}

function groupByMonth(bookings: HostBooking[]): MonthlyGroup[] {
  const map = new Map<string, HostBooking[]>();
  bookings
    .filter((b) => b.status !== 'cancelled')
    .forEach((b) => {
      const d = new Date(b.bookedAt);
      const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
      map.set(key, [...(map.get(key) ?? []), b]);
    });
  return Array.from(map.entries())
    .sort(([a], [b]) => b.localeCompare(a))
    .map(([key, bks]) => {
      const [yr, mo] = key.split('-').map(Number);
      const label = new Date(yr, mo - 1, 1).toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });
      return {
        key,
        label,
        year: yr,
        month: mo,
        bookings: bks,
        grossRevenue: bks.reduce((s, b) => s + b.totalAmount, 0),
        platformFee: bks.reduce((s, b) => s + b.platformFee, 0),
        netEarnings: bks.reduce((s, b) => s + b.hostEarnings, 0),
        bookingCount: bks.length,
        totalNights: bks.reduce((s, b) => s + b.nights, 0),
      };
    });
}

// ── CSV generator ──────────────────────────────────────────────────────────
function downloadCSV(filename: string, rows: string[][]): void {
  const csv = rows
    .map((r) =>
      r.map((cell) => (cell.includes(',') || cell.includes('"') || cell.includes('\n')
        ? `"${cell.replace(/"/g, '""')}"` : cell))
        .join(',')
    )
    .join('\n');
  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// ── Print / PDF generator ──────────────────────────────────────────────────
function printReport(htmlContent: string, title: string): void {
  const win = window.open('', '_blank', 'width=900,height=700');
  if (!win) return;
  win.document.write(`<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', Arial, sans-serif; color: #1c1917; background: #fff; padding: 40px; font-size: 13px; }
    h1 { font-size: 22px; font-weight: 700; margin-bottom: 4px; }
    h2 { font-size: 15px; font-weight: 600; margin: 24px 0 10px; color: #44403c; border-bottom: 1px solid #e7e5e4; padding-bottom: 6px; }
    .meta { color: #78716c; font-size: 12px; margin-bottom: 28px; }
    .header-row { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 28px; }
    .logo { font-size: 18px; font-weight: 800; letter-spacing: -0.5px; }
    .logo span { color: #d97706; }
    .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 24px; }
    .stat-card { background: #fafaf9; border: 1px solid #e7e5e4; border-radius: 8px; padding: 12px 14px; }
    .stat-card .val { font-size: 18px; font-weight: 700; color: #1c1917; }
    .stat-card .lbl { font-size: 11px; color: #78716c; margin-top: 2px; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    th { background: #1c1917; color: #fff; padding: 8px 10px; text-align: left; font-weight: 600; font-size: 11px; letter-spacing: 0.03em; }
    td { padding: 8px 10px; border-bottom: 1px solid #f5f5f4; }
    tr:nth-child(even) td { background: #fafaf9; }
    .amount { text-align: right; font-weight: 600; }
    .fee { color: #dc2626; }
    .net { color: #059669; font-weight: 700; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e7e5e4; font-size: 11px; color: #a8a29e; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 99px; font-size: 10px; font-weight: 600; }
    .badge-green { background: #d1fae5; color: #065f46; }
    .badge-amber { background: #fef3c7; color: #92400e; }
    .badge-stone { background: #f5f5f4; color: #57534e; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  ${htmlContent}
  <div class="footer">
    <p>Generated by Triprodeo Owner Portal on ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}</p>
    <p style="margin-top:4px">This document is auto-generated. For disputes contact host-support@triprodeo.com</p>
  </div>
  <script>window.onload = () => { window.print(); }<\/script>
</body>
</html>`);
  win.document.close();
}

// ── Report type meta ───────────────────────────────────────────────────────
const reportTypes: { id: ReportType; label: string; icon: string; desc: string; badge: string }[] = [
  { id: 'earnings', label: 'Monthly Earnings Report', icon: 'ri-money-rupee-circle-line', desc: 'Gross revenue, platform fees, and net earnings grouped by month', badge: 'CSV + PDF' },
  { id: 'bookings', label: 'Booking Statement', icon: 'ri-calendar-check-line', desc: 'Full list of all bookings with guest details and payment breakdown', badge: 'CSV + PDF' },
  { id: 'tax', label: 'Tax Summary (TDS)', icon: 'ri-file-text-line', desc: 'TDS deductions at 5% for income tax filing (Form 26AS reference)', badge: 'PDF' },
  { id: 'gst', label: 'GST Report', icon: 'ri-receipt-line', desc: 'CGST + SGST breakdown per booking for GST return filing (18% on platform fee)', badge: 'PDF' },
];

const statusBadge = (s: string) => {
  if (s === 'confirmed') return '<span class="badge badge-green">Confirmed</span>';
  if (s === 'completed') return '<span class="badge badge-stone">Completed</span>';
  if (s === 'pending')   return '<span class="badge badge-amber">Pending</span>';
  return '<span class="badge badge-stone">Cancelled</span>';
};

export default function HostReportsView({ host, bookings, properties }: Props) {
  const [selectedYear, setSelectedYear] = useState<number>(new Date().getFullYear());
  const [selectedMonth, setSelectedMonth] = useState<number>(0); // 0 = full year
  const [selectedProperty, setSelectedProperty] = useState<string>('all');
  const [downloading, setDownloading] = useState<ReportType | null>(null);
  const [successMsg, setSuccessMsg] = useState('');

  const availableYears = useMemo(() => {
    const years = new Set<number>();
    bookings.forEach((b) => years.add(new Date(b.bookedAt).getFullYear()));
    years.add(new Date().getFullYear());
    return Array.from(years).sort((a, b) => b - a);
  }, [bookings]);

  const filteredBookings = useMemo(() => {
    return bookings.filter((b) => {
      const d = new Date(b.bookedAt);
      const matchYear = d.getFullYear() === selectedYear;
      const matchMonth = selectedMonth === 0 || d.getMonth() + 1 === selectedMonth;
      const matchProp = selectedProperty === 'all' || b.propertyId === selectedProperty;
      return matchYear && matchMonth && matchProp && b.status !== 'cancelled';
    });
  }, [bookings, selectedYear, selectedMonth, selectedProperty]);

  const monthlyGroups = useMemo(() => groupByMonth(filteredBookings), [filteredBookings]);

  // Summary totals
  const totalGross = filteredBookings.reduce((s, b) => s + b.totalAmount, 0);
  const totalFees  = filteredBookings.reduce((s, b) => s + b.platformFee, 0);
  const totalNet   = filteredBookings.reduce((s, b) => s + b.hostEarnings, 0);
  const totalNights = filteredBookings.reduce((s, b) => s + b.nights, 0);

  const periodLabel = selectedMonth === 0
    ? `FY ${selectedYear}`
    : new Date(selectedYear, selectedMonth - 1, 1).toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });

  const triggerDownload = (type: ReportType, mode: 'csv' | 'pdf') => {
    setDownloading(type);
    setTimeout(() => {
      try {
        if (type === 'earnings') {
          if (mode === 'csv') downloadEarningsCSV();
          else printEarningsPDF();
        } else if (type === 'bookings') {
          if (mode === 'csv') downloadBookingsCSV();
          else printBookingsPDF();
        } else if (type === 'tax') {
          printTaxPDF();
        } else if (type === 'gst') {
          printGSTPDF();
        }
        setSuccessMsg(`${reportTypes.find((r) => r.id === type)?.label} downloaded!`);
        setTimeout(() => setSuccessMsg(''), 3000);
      } finally {
        setDownloading(null);
      }
    }, 400);
  };

  // ── EARNINGS CSV ──────────────────────────────────────────────────────────
  const downloadEarningsCSV = () => {
    const header = ['Month', 'Bookings', 'Total Nights', 'Gross Revenue (₹)', 'Platform Fee (₹)', 'Net Earnings (₹)'];
    const rows = monthlyGroups.map((m) => [
      m.label, String(m.bookingCount), String(m.totalNights),
      String(m.grossRevenue), String(m.platformFee), String(m.netEarnings),
    ]);
    rows.push(['', '', '', '', '', '']);
    rows.push(['TOTAL', String(filteredBookings.length), String(totalNights),
      String(totalGross), String(totalFees), String(totalNet)]);
    downloadCSV(`triprodeo_earnings_${periodLabel.replace(/\s/g, '_')}.csv`, [header, ...rows]);
  };

  // ── BOOKINGS CSV ──────────────────────────────────────────────────────────
  const downloadBookingsCSV = () => {
    const header = ['Booking ID', 'Guest Name', 'Guest Email', 'Guest Phone', 'Property', 'Check-in', 'Check-out',
      'Nights', 'Guests', 'Rate/Night (₹)', 'Total Amount (₹)', 'Platform Fee (₹)', 'Net Earnings (₹)',
      'Payment Method', 'Status', 'Booked On'];
    const rows = filteredBookings
      .sort((a, b) => new Date(b.bookedAt).getTime() - new Date(a.bookedAt).getTime())
      .map((b) => [
        b.id, b.guestName, b.guestEmail, b.guestPhone, b.propertyName,
        b.checkIn, b.checkOut, String(b.nights), String(b.guestCount),
        String(b.pricePerNight), String(b.totalAmount), String(b.platformFee), String(b.hostEarnings),
        b.paymentMethod, b.status, new Date(b.bookedAt).toLocaleDateString('en-IN'),
      ]);
    downloadCSV(`triprodeo_bookings_${periodLabel.replace(/\s/g, '_')}.csv`, [header, ...rows]);
  };

  // ── EARNINGS PDF ──────────────────────────────────────────────────────────
  const printEarningsPDF = () => {
    const html = `
      <div class="header-row">
        <div><div class="logo">Tripro<span>deo</span></div><p class="meta" style="margin-top:4px">Property Owner Earnings Report · ${periodLabel} · ${host.name}</p></div>
        <div style="text-align:right"><p style="font-size:11px;color:#78716c">Generated</p><p style="font-weight:600">${new Date().toLocaleDateString('en-IN')}</p></div>
      </div>
      <div class="stats">
        <div class="stat-card"><div class="val">₹${totalGross.toLocaleString('en-IN')}</div><div class="lbl">Gross Revenue</div></div>
        <div class="stat-card"><div class="val" style="color:#dc2626">₹${totalFees.toLocaleString('en-IN')}</div><div class="lbl">Platform Fees (10%)</div></div>
        <div class="stat-card"><div class="val" style="color:#059669">₹${totalNet.toLocaleString('en-IN')}</div><div class="lbl">Net Earnings</div></div>
        <div class="stat-card"><div class="val">${filteredBookings.length}</div><div class="lbl">Total Bookings</div></div>
      </div>
      <h2>Monthly Breakdown</h2>
      <table>
        <thead><tr><th>Month</th><th>Bookings</th><th>Nights</th><th class="amount">Gross Revenue</th><th class="amount">Platform Fee</th><th class="amount">Net Earnings</th></tr></thead>
        <tbody>
          ${monthlyGroups.map((m) => `
            <tr>
              <td>${m.label}</td>
              <td>${m.bookingCount}</td>
              <td>${m.totalNights}</td>
              <td class="amount">₹${m.grossRevenue.toLocaleString('en-IN')}</td>
              <td class="amount fee">₹${m.platformFee.toLocaleString('en-IN')}</td>
              <td class="amount net">₹${m.netEarnings.toLocaleString('en-IN')}</td>
            </tr>`).join('')}
          <tr style="border-top:2px solid #1c1917">
            <td><strong>TOTAL</strong></td>
            <td><strong>${filteredBookings.length}</strong></td>
            <td><strong>${totalNights}</strong></td>
            <td class="amount"><strong>₹${totalGross.toLocaleString('en-IN')}</strong></td>
            <td class="amount fee"><strong>₹${totalFees.toLocaleString('en-IN')}</strong></td>
            <td class="amount net"><strong>₹${totalNet.toLocaleString('en-IN')}</strong></td>
          </tr>
        </tbody>
      </table>`;
    printReport(html, `Earnings Report – ${periodLabel}`);
  };

  // ── BOOKINGS PDF ──────────────────────────────────────────────────────────
  const printBookingsPDF = () => {
    const sorted = [...filteredBookings].sort((a, b) => new Date(b.bookedAt).getTime() - new Date(a.bookedAt).getTime());
    const html = `
      <div class="header-row">
        <div><div class="logo">Tripro<span>deo</span></div><p class="meta" style="margin-top:4px">Booking Statement · ${periodLabel} · ${host.name}</p></div>
        <div style="text-align:right"><p style="font-size:11px;color:#78716c">Generated</p><p style="font-weight:600">${new Date().toLocaleDateString('en-IN')}</p></div>
      </div>
      <div class="stats">
        <div class="stat-card"><div class="val">${sorted.length}</div><div class="lbl">Total Bookings</div></div>
        <div class="stat-card"><div class="val">${totalNights}</div><div class="lbl">Total Nights</div></div>
        <div class="stat-card"><div class="val" style="color:#059669">₹${totalNet.toLocaleString('en-IN')}</div><div class="lbl">Net Earnings</div></div>
        <div class="stat-card"><div class="val">₹${sorted.length > 0 ? Math.round(totalGross / sorted.length).toLocaleString('en-IN') : 0}</div><div class="lbl">Avg. Booking Value</div></div>
      </div>
      <h2>All Bookings</h2>
      <table>
        <thead><tr><th>Guest</th><th>Property</th><th>Check-in</th><th>Check-out</th><th>Nights</th><th>Status</th><th class="amount">Net Earnings</th></tr></thead>
        <tbody>
          ${sorted.map((b) => `
            <tr>
              <td><strong>${b.guestName}</strong><br><span style="color:#78716c;font-size:11px">${b.guestEmail}</span></td>
              <td>${b.propertyName}</td>
              <td>${b.checkIn}</td>
              <td>${b.checkOut}</td>
              <td>${b.nights}</td>
              <td>${statusBadge(b.status)}</td>
              <td class="amount net">₹${b.hostEarnings.toLocaleString('en-IN')}</td>
            </tr>`).join('')}
        </tbody>
      </table>`;
    printReport(html, `Booking Statement – ${periodLabel}`);
  };

  // ── TAX PDF (TDS) ─────────────────────────────────────────────────────────
  const printTaxPDF = () => {
    const TDS_RATE = 0.05;
    const tdsDeducted = Math.round(totalNet * TDS_RATE);
    const netAfterTDS = totalNet - tdsDeducted;
    const sorted = [...filteredBookings].sort((a, b) => new Date(b.bookedAt).getTime() - new Date(a.bookedAt).getTime());
    const html = `
      <div class="header-row">
        <div><div class="logo">Tripro<span>deo</span></div><p class="meta" style="margin-top:4px">TDS Summary Report · ${periodLabel} · ${host.name}</p></div>
        <div style="text-align:right"><p style="font-size:11px;color:#78716c">Generated</p><p style="font-weight:600">${new Date().toLocaleDateString('en-IN')}</p></div>
      </div>
      <div style="background:#fef3c7;border:1px solid #fde68a;border-radius:8px;padding:12px 16px;margin-bottom:20px;font-size:12px;color:#92400e">
        <strong>Disclaimer:</strong> This document is for reference only. TDS rates may vary based on PAN status and applicable provisions under the Income Tax Act, 1961. Consult your CA for accurate tax filing.
      </div>
      <div class="stats">
        <div class="stat-card"><div class="val">₹${totalNet.toLocaleString('en-IN')}</div><div class="lbl">Total Net Earnings</div></div>
        <div class="stat-card"><div class="val" style="color:#dc2626">₹${tdsDeducted.toLocaleString('en-IN')}</div><div class="lbl">TDS @ 5% (Sec 194C)</div></div>
        <div class="stat-card"><div class="val" style="color:#059669">₹${netAfterTDS.toLocaleString('en-IN')}</div><div class="lbl">Amount After TDS</div></div>
        <div class="stat-card"><div class="val">${filteredBookings.length}</div><div class="lbl">Transactions</div></div>
      </div>
      <h2>Deductor Details</h2>
      <table>
        <thead><tr><th>Field</th><th>Details</th></tr></thead>
        <tbody>
          <tr><td>Deductor Name</td><td>Triprodeo Technologies Pvt. Ltd.</td></tr>
          <tr><td>TAN (Tax Deduction Account Number)</td><td>DELP12345A (Reference only)</td></tr>
          <tr><td>PAN of Deductee</td><td>${host.name.toUpperCase().replace(/\s/g, '').slice(0, 5)}XXXXX</td></tr>
          <tr><td>Section</td><td>194C – Payments to Contractors</td></tr>
          <tr><td>Financial Year</td><td>${selectedYear}-${String(selectedYear + 1).slice(2)}</td></tr>
        </tbody>
      </table>
      <h2>Monthly TDS Breakdown</h2>
      <table>
        <thead><tr><th>Month</th><th class="amount">Net Earnings</th><th class="amount">TDS @ 5%</th><th class="amount">Amount Credited</th></tr></thead>
        <tbody>
          ${monthlyGroups.map((m) => {
            const tds = Math.round(m.netEarnings * TDS_RATE);
            return `<tr>
              <td>${m.label}</td>
              <td class="amount">₹${m.netEarnings.toLocaleString('en-IN')}</td>
              <td class="amount fee">₹${tds.toLocaleString('en-IN')}</td>
              <td class="amount net">₹${(m.netEarnings - tds).toLocaleString('en-IN')}</td>
            </tr>`;
          }).join('')}
          <tr style="border-top:2px solid #1c1917">
            <td><strong>TOTAL</strong></td>
            <td class="amount"><strong>₹${totalNet.toLocaleString('en-IN')}</strong></td>
            <td class="amount fee"><strong>₹${tdsDeducted.toLocaleString('en-IN')}</strong></td>
            <td class="amount net"><strong>₹${netAfterTDS.toLocaleString('en-IN')}</strong></td>
          </tr>
        </tbody>
      </table>
      <h2>Transaction Details (Form 26AS Reference)</h2>
      <table>
        <thead><tr><th>Booking ID</th><th>Guest</th><th>Property</th><th>Date</th><th class="amount">Amount (₹)</th><th class="amount">TDS (₹)</th></tr></thead>
        <tbody>
          ${sorted.map((b) => {
            const tds = Math.round(b.hostEarnings * TDS_RATE);
            return `<tr>
              <td style="font-size:11px">${b.id}</td>
              <td>${b.guestName}</td>
              <td>${b.propertyName}</td>
              <td>${new Date(b.bookedAt).toLocaleDateString('en-IN')}</td>
              <td class="amount">₹${b.hostEarnings.toLocaleString('en-IN')}</td>
              <td class="amount fee">₹${tds.toLocaleString('en-IN')}</td>
            </tr>`;
          }).join('')}
        </tbody>
      </table>`;
    printReport(html, `TDS Summary – ${periodLabel}`);
  };

  // ── GST PDF ───────────────────────────────────────────────────────────────
  const printGSTPDF = () => {
    const GST_RATE = 0.18;
    const totalGST = Math.round(totalFees * GST_RATE);
    const cgst = Math.round(totalGST / 2);
    const sgst = totalGST - cgst;
    const sorted = [...filteredBookings].sort((a, b) => new Date(b.bookedAt).getTime() - new Date(a.bookedAt).getTime());
    const html = `
      <div class="header-row">
        <div><div class="logo">Tripro<span>deo</span></div><p class="meta" style="margin-top:4px">GST Report · ${periodLabel} · ${host.name}</p></div>
        <div style="text-align:right"><p style="font-size:11px;color:#78716c">Generated</p><p style="font-weight:600">${new Date().toLocaleDateString('en-IN')}</p></div>
      </div>
      <div style="background:#fef3c7;border:1px solid #fde68a;border-radius:8px;padding:12px 16px;margin-bottom:20px;font-size:12px;color:#92400e">
        <strong>Disclaimer:</strong> GST is levied on the platform service fee charged by Triprodeo (18%). This report is for reference. Verify with your GST consultant before filing returns.
      </div>
      <div class="stats">
        <div class="stat-card"><div class="val">₹${totalFees.toLocaleString('en-IN')}</div><div class="lbl">Taxable Value (Platform Fee)</div></div>
        <div class="stat-card"><div class="val">₹${cgst.toLocaleString('en-IN')}</div><div class="lbl">CGST @ 9%</div></div>
        <div class="stat-card"><div class="val">₹${sgst.toLocaleString('en-IN')}</div><div class="lbl">SGST @ 9%</div></div>
        <div class="stat-card"><div class="val" style="color:#dc2626">₹${totalGST.toLocaleString('en-IN')}</div><div class="lbl">Total GST @ 18%</div></div>
      </div>
      <h2>Supplier Details</h2>
      <table>
        <thead><tr><th>Field</th><th>Details</th></tr></thead>
        <tbody>
          <tr><td>Supplier Name</td><td>Triprodeo Technologies Pvt. Ltd.</td></tr>
          <tr><td>GSTIN</td><td>29ABCDE1234F1ZX (Reference only)</td></tr>
          <tr><td>Service Type</td><td>Online Information & Database Access (OIDAR)</td></tr>
          <tr><td>SAC Code</td><td>998314 – Short-term accommodation rental</td></tr>
          <tr><td>Place of Supply</td><td>As per booking location</td></tr>
        </tbody>
      </table>
      <h2>Monthly GST Summary</h2>
      <table>
        <thead><tr><th>Month</th><th class="amount">Taxable Value</th><th class="amount">CGST (9%)</th><th class="amount">SGST (9%)</th><th class="amount">Total GST</th></tr></thead>
        <tbody>
          ${monthlyGroups.map((m) => {
            const gst = Math.round(m.platformFee * GST_RATE);
            const c = Math.round(gst / 2);
            const s = gst - c;
            return `<tr>
              <td>${m.label}</td>
              <td class="amount">₹${m.platformFee.toLocaleString('en-IN')}</td>
              <td class="amount">₹${c.toLocaleString('en-IN')}</td>
              <td class="amount">₹${s.toLocaleString('en-IN')}</td>
              <td class="amount fee">₹${gst.toLocaleString('en-IN')}</td>
            </tr>`;
          }).join('')}
          <tr style="border-top:2px solid #1c1917">
            <td><strong>TOTAL</strong></td>
            <td class="amount"><strong>₹${totalFees.toLocaleString('en-IN')}</strong></td>
            <td class="amount"><strong>₹${cgst.toLocaleString('en-IN')}</strong></td>
            <td class="amount"><strong>₹${sgst.toLocaleString('en-IN')}</strong></td>
            <td class="amount fee"><strong>₹${totalGST.toLocaleString('en-IN')}</strong></td>
          </tr>
        </tbody>
      </table>
      <h2>Invoice-wise GST Details (GSTR-1 Reference)</h2>
      <table>
        <thead><tr><th>Booking ID</th><th>Guest</th><th>Property</th><th>Date</th><th class="amount">Platform Fee</th><th class="amount">GST (18%)</th></tr></thead>
        <tbody>
          ${sorted.map((b) => {
            const gst = Math.round(b.platformFee * GST_RATE);
            return `<tr>
              <td style="font-size:11px">${b.id}</td>
              <td>${b.guestName}</td>
              <td>${b.propertyName}</td>
              <td>${new Date(b.bookedAt).toLocaleDateString('en-IN')}</td>
              <td class="amount">₹${b.platformFee.toLocaleString('en-IN')}</td>
              <td class="amount fee">₹${gst.toLocaleString('en-IN')}</td>
            </tr>`;
          }).join('')}
        </tbody>
      </table>`;
    printReport(html, `GST Report – ${periodLabel}`);
  };

  const months = [
    { val: 0, label: 'Full Year' },
    ...Array.from({ length: 12 }, (_, i) => ({
      val: i + 1,
      label: new Date(2024, i, 1).toLocaleDateString('en-IN', { month: 'long' }),
    })),
  ];

  return (
    <div>
      {/* Header */}
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-stone-900">Reports & Documents</h1>
        <p className="text-stone-500 text-sm mt-1">Download earnings reports, booking statements, and tax documents</p>
      </div>

      {/* Success toast */}
      {successMsg && (
        <div className="mb-5 px-4 py-3 bg-green-50 border border-green-200 rounded-xl flex items-center gap-2 text-green-700 text-sm">
          <i className="ri-checkbox-circle-line text-base" />
          {successMsg}
        </div>
      )}

      {/* Period selector */}
      <div className="bg-white rounded-2xl border border-stone-200 p-5 mb-6">
        <h2 className="font-semibold text-stone-900 text-sm mb-4 flex items-center gap-2">
          <i className="ri-filter-3-line text-stone-400" /> Report Period &amp; Filters
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div>
            <label className="block text-xs font-medium text-stone-500 mb-1.5">Year</label>
            <select
              value={selectedYear}
              onChange={(e) => setSelectedYear(Number(e.target.value))}
              className="w-full px-3 py-2.5 border border-stone-200 rounded-xl text-sm text-stone-700 focus:outline-none focus:border-stone-400 bg-white cursor-pointer"
            >
              {availableYears.map((y) => (
                <option key={y} value={y}>{y}</option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-xs font-medium text-stone-500 mb-1.5">Month</label>
            <select
              value={selectedMonth}
              onChange={(e) => setSelectedMonth(Number(e.target.value))}
              className="w-full px-3 py-2.5 border border-stone-200 rounded-xl text-sm text-stone-700 focus:outline-none focus:border-stone-400 bg-white cursor-pointer"
            >
              {months.map((m) => (
                <option key={m.val} value={m.val}>{m.label}</option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-xs font-medium text-stone-500 mb-1.5">Property</label>
            <select
              value={selectedProperty}
              onChange={(e) => setSelectedProperty(e.target.value)}
              className="w-full px-3 py-2.5 border border-stone-200 rounded-xl text-sm text-stone-700 focus:outline-none focus:border-stone-400 bg-white cursor-pointer"
            >
              <option value="all">All Properties</option>
              {properties.map((p) => (
                <option key={p.id} value={p.id}>{p.name}</option>
              ))}
            </select>
          </div>
        </div>

        {/* Period summary strip */}
        <div className="mt-4 pt-4 border-t border-stone-100 grid grid-cols-2 sm:grid-cols-4 gap-3">
          {[
            { label: 'Period', value: periodLabel, icon: 'ri-calendar-line' },
            { label: 'Bookings', value: String(filteredBookings.length), icon: 'ri-calendar-check-line' },
            { label: 'Gross Revenue', value: `₹${totalGross.toLocaleString('en-IN')}`, icon: 'ri-money-rupee-circle-line' },
            { label: 'Net Earnings', value: `₹${totalNet.toLocaleString('en-IN')}`, icon: 'ri-hand-coin-line' },
          ].map((s) => (
            <div key={s.label} className="flex items-center gap-2">
              <div className="w-7 h-7 flex items-center justify-center bg-stone-100 rounded-lg flex-shrink-0">
                <i className={`${s.icon} text-stone-500 text-xs`} />
              </div>
              <div>
                <p className="text-xs text-stone-400">{s.label}</p>
                <p className="text-sm font-bold text-stone-800">{s.value}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Report cards */}
      <div className="space-y-4">
        {reportTypes.map((rt) => {
          const isLoading = downloading === rt.id;
          const isEarnings = rt.id === 'earnings';
          const isBookings = rt.id === 'bookings';
          const hasCsv = isEarnings || isBookings;

          return (
            <div key={rt.id} className="bg-white rounded-2xl border border-stone-200 p-5">
              <div className="flex items-start gap-4">
                {/* Icon */}
                <div className="w-12 h-12 flex items-center justify-center bg-stone-100 rounded-2xl flex-shrink-0">
                  <i className={`${rt.icon} text-stone-600 text-xl`} />
                </div>

                {/* Info */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap mb-1">
                    <h3 className="font-bold text-stone-900">{rt.label}</h3>
                    <span className="px-2 py-0.5 bg-amber-100 text-amber-700 text-xs font-semibold rounded-full">
                      {rt.badge}
                    </span>
                  </div>
                  <p className="text-stone-500 text-sm">{rt.desc}</p>

                  {/* Preview rows for earnings/bookings */}
                  {isEarnings && monthlyGroups.length > 0 && (
                    <div className="mt-3 space-y-1.5">
                      {monthlyGroups.slice(0, 3).map((m) => (
                        <div key={m.key} className="flex items-center gap-3 text-xs text-stone-500">
                          <span className="w-28 font-medium text-stone-700 flex-shrink-0">{m.label}</span>
                          <span>{m.bookingCount} booking{m.bookingCount !== 1 ? 's' : ''}</span>
                          <span className="ml-auto font-semibold text-emerald-600">
                            ₹{m.netEarnings.toLocaleString('en-IN')}
                          </span>
                        </div>
                      ))}
                      {monthlyGroups.length > 3 && (
                        <p className="text-xs text-stone-400 mt-1">+{monthlyGroups.length - 3} more months in report</p>
                      )}
                    </div>
                  )}

                  {(rt.id === 'tax' || rt.id === 'gst') && (
                    <div className="mt-3 flex flex-wrap gap-3 text-xs">
                      {rt.id === 'tax' && (
                        <>
                          <span className="px-2.5 py-1 bg-stone-50 border border-stone-200 rounded-lg text-stone-600">
                            TDS @ 5% = ₹{Math.round(totalNet * 0.05).toLocaleString('en-IN')}
                          </span>
                          <span className="px-2.5 py-1 bg-stone-50 border border-stone-200 rounded-lg text-stone-600">
                            Section 194C
                          </span>
                          <span className="px-2.5 py-1 bg-stone-50 border border-stone-200 rounded-lg text-stone-600">
                            Form 26AS ref
                          </span>
                        </>
                      )}
                      {rt.id === 'gst' && (
                        <>
                          <span className="px-2.5 py-1 bg-stone-50 border border-stone-200 rounded-lg text-stone-600">
                            CGST ₹{Math.round(totalFees * 0.09).toLocaleString('en-IN')} + SGST ₹{Math.round(totalFees * 0.09).toLocaleString('en-IN')}
                          </span>
                          <span className="px-2.5 py-1 bg-stone-50 border border-stone-200 rounded-lg text-stone-600">
                            SAC 998314
                          </span>
                          <span className="px-2.5 py-1 bg-stone-50 border border-stone-200 rounded-lg text-stone-600">
                            GSTR-1 ref
                          </span>
                        </>
                      )}
                    </div>
                  )}
                </div>

                {/* Action buttons */}
                <div className="flex flex-col gap-2 flex-shrink-0">
                  <button
                    onClick={() => triggerDownload(rt.id, 'pdf')}
                    disabled={isLoading || filteredBookings.length === 0}
                    className="flex items-center gap-2 px-4 py-2 bg-stone-900 text-white rounded-xl text-xs font-semibold hover:bg-stone-700 transition-colors cursor-pointer whitespace-nowrap disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {isLoading ? (
                      <i className="ri-loader-4-line animate-spin" />
                    ) : (
                      <i className="ri-printer-line" />
                    )}
                    {isLoading ? 'Preparing...' : 'Print / PDF'}
                  </button>
                  {hasCsv && (
                    <button
                      onClick={() => triggerDownload(rt.id, 'csv')}
                      disabled={isLoading || filteredBookings.length === 0}
                      className="flex items-center gap-2 px-4 py-2 border border-stone-200 text-stone-700 rounded-xl text-xs font-semibold hover:bg-stone-50 transition-colors cursor-pointer whitespace-nowrap disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      <i className="ri-file-excel-2-line" />
                      Download CSV
                    </button>
                  )}
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Empty state */}
      {filteredBookings.length === 0 && (
        <div className="mt-5 p-5 bg-amber-50 border border-amber-200 rounded-2xl flex items-start gap-3">
          <i className="ri-information-line text-amber-500 text-lg flex-shrink-0 mt-0.5" />
          <div>
            <p className="font-semibold text-amber-800 text-sm">No bookings for selected period</p>
            <p className="text-amber-700 text-xs mt-1">
              No data found for <strong>{periodLabel}</strong>. Try selecting a different year, month, or property.
            </p>
          </div>
        </div>
      )}

      {/* Tax disclaimer */}
      <div className="mt-6 p-4 bg-stone-50 border border-stone-200 rounded-2xl flex items-start gap-3">
        <i className="ri-shield-check-line text-stone-400 text-lg flex-shrink-0 mt-0.5" />
        <div>
          <p className="font-semibold text-stone-700 text-sm">Legal Disclaimer</p>
          <p className="text-stone-500 text-xs mt-1 leading-relaxed">
            All reports are auto-generated for informational purposes only. Tax rates (TDS 5%, GST 18%) are indicative.
            Actual obligations may differ based on your tax status, PAN availability, and applicable exemptions.
            Please consult a Chartered Accountant for official tax filing. Triprodeo is not liable for any tax discrepancies.
          </p>
        </div>
      </div>
    </div>
  );
}
